import { readFile, readdir, writeFile } from 'fs/promises'
import { spawnSync } from 'child_process'
import { basename, join } from 'path'
import { codeToHtml } from 'shiki'

const examplesDir = 'examples'
const examplesReadmePath = join(examplesDir, 'README.md')
const outDir = 'docs/assets/examples'
const galleryAssetUrl = 'https://bvolpato.github.io/vizmatic/assets/examples'
const themes = ['dark', 'light'] as const
const files = (await readdir(examplesDir))
    .filter((file) => file.endsWith('.tsx'))
    .sort()

const manifest: Array<{ name: string; source: string; outputs: string[] }> = []
const sources: Array<{ name: string; title: string; source: string; code: string; html: Record<(typeof themes)[number], string> }> = []
const titleWords: Record<string, string> = {
    gif: 'GIF',
    rag: 'RAG',
}

function titleFor(name: string): string {
    return name
        .split('-')
        .map((part) => titleWords[part] ?? part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ')
}

function previewFor(outputs: string[], theme: (typeof themes)[number]): string {
    return outputs.find((output) => output.endsWith(`_${theme}.gif`))
        ?? outputs.find((output) => output.endsWith(`_${theme}.png`))
        ?? outputs[0]
        ?? ''
}

function sourceForGallery(code: string): string {
    if (!code.includes('createScenes')) return code
    return code
        .replace(/\nexport function create\(theme: ThemeMode = 'dark'\) \{\n    return buildFrame\(theme, stages\.length - 1\)\n\}\n(?=\nexport function createScenes)/, '\n')
        .replace(/\nexport default create\('dark'\)\n?$/, '\n')
        .replace(/\n{3,}/g, '\n\n')
}

function generateExamplesReadme(entries: typeof manifest): string {
    const rows = entries.map((entry) => {
        const title = titleFor(entry.name)
        const sourceFile = basename(entry.source)
        const dark = previewFor(entry.outputs, 'dark')
        const light = previewFor(entry.outputs, 'light')

        return `| [${title}](${sourceFile}) | <img src="${galleryAssetUrl}/${dark}" alt="${title} dark render" width="360" /> | <img src="${galleryAssetUrl}/${light}" alt="${title} light render" width="360" /> |`
    })

    return [
        '# Vizmatic examples',
        '',
        'Generated by `pnpm render:examples`. Edit the `.tsx` sources, then run that command again to refresh these previews.',
        '',
        'Rendered assets live on the [Vizmatic gallery](https://bvolpato.github.io/vizmatic/#gallery).',
        '',
        '| Example | Dark | Light |',
        '|---|---|---|',
        ...rows,
        '',
    ].join('\n')
}

for (const file of files) {
    const source = join(examplesDir, file)
    const name = basename(file, '.tsx')
    const renderArgs = [
        'dist/cli.js',
        'render',
        source,
        '--out',
        outDir,
        '--theme',
        themes.join(','),
    ]
    if (name !== 'vizmatic-hero') renderArgs.push('--watermark', 'Vizmatic')

    const result = spawnSync(process.execPath, renderArgs, {
        stdio: 'inherit',
    })

    if (result.status !== 0) {
        process.exit(result.status ?? 1)
    }

    const code = sourceForGallery(await readFile(source, 'utf8'))
    const html = Object.fromEntries(await Promise.all(themes.map(async (theme) => [
        theme,
        await codeToHtml(code, {
            lang: 'tsx',
            theme: theme === 'light' ? 'github-light-high-contrast' : 'github-dark-high-contrast',
        }),
    ]))) as Record<(typeof themes)[number], string>

    sources.push({
        name,
        title: titleFor(name),
        source,
        code,
        html,
    })

    const outputs = themes.map((theme) => `${name}_${theme}.png`)

    if (code.includes('createScenes')) {
        const gifResult = spawnSync(process.execPath, [
            'dist/cli.js',
            'gif',
            source,
            '--out',
            outDir,
            '--theme',
            themes.join(','),
            '--watermark',
            'Vizmatic',
            '--scale',
            '1',
        ], {
            stdio: 'inherit',
        })

        if (gifResult.status !== 0) {
            process.exit(gifResult.status ?? 1)
        }

        outputs.push(...themes.map((theme) => `${name}_${theme}.gif`))
    }

    manifest.push({
        name,
        source,
        outputs,
    })
}

await writeFile(join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`)
await writeFile(join(outDir, 'sources.json'), `${JSON.stringify(sources, null, 2)}\n`)
await writeFile(examplesReadmePath, generateExamplesReadme(manifest))
console.log(`rendered ${files.length} example frames in ${themes.join('/')} themes`)
